import localFont from "next/font/local";
import "./globals.css";
import Header from "/components/Header.jsx";
import Sidebar from "/components/Sidebar.jsx";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Cyber Drill",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div><Header/></div>
        <div className="flex">
          <div className="w-1/4">
            <Sidebar/>
          </div>
          <div className="w-full">{children}</div>
        </div>
      </body>
    </html>
  );
}
